### ISSUE TITLE
Persistant issues with data partially only being downloaded

### ISSUE THREAD

**Issue by dalepotter** [IATI/IATI-Registry-Refresher#18] opened 2016-10-26 14:39 UTC
There appears to be a problem with the downloading of IATI data as part of the nightly Dashboard generation process. This is shown by the results below:

```
~/IATI-Registry-Refresher$ cd urls
~/IATI-Registry-Refresher/urls$ ls -lh | wc -l
599
~/IATI-Registry-Refresher/urls$ cd ../data
~/IATI-Registry-Refresher/data$ ls -lh | wc -l
194
```

The number of files downloaded seems to vary each day. Additionally, all data appears to download correctly when the registry refresher is run manually.

This is a priority to fix as it is causing failures in the process to generate the [IATI Dashboard](http://dashboard.iatistandard.org/).

**Comment by andylolz** [comment] 2018-01-11 11:09
Is this still an issue?
Is it possible this was caused by issues with the registry?

**Comment by Ocre42** [comment] 2019-01-15 15:16
Testing this on several instances of the dashboard (local, test droplet, dev, live) appears to confirm this ticket is no longer relevant. Closing.

**Closed by Ocre42** 2019-01-15 15:16 UTC
Labels: bug
